- name: prepare VM in Azure cloud for Node developement
  hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python
    directory: learn
  tasks: 
  - name: install nodejs
    apt: 
      name: nodejs
      state: present
    become: yes


